---
- name: Install UV package manager
  shell: curl -LsSf https://astral.sh/uv/0.8.11/install.sh | sh
  environment:
    UV_INSTALL_DIR: /usr/local/bin
  become: yes

- name: Add UV to PATH in bashrc
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: 'export PATH="/usr/local/bin:$PATH"'
    create: yes

- name: Verify UV installation
  shell: /usr/local/bin/uv --version
  register: uv_version
  failed_when: uv_version.rc != 0

- name: Display UV version
  debug:
    msg: "UV version: {{ uv_version.stdout }}"