---
- name: Deploy Mistral 7B Service with bentoML
  hosts: all
  become: yes
  vars_files:
    - ../vars/main.yml
    

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  roles:
    - role: docker
    - role: uv
    - role: bentoml
    # - role: nginx
    # - role: monitoring 